name: pcom_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.8.0

dependencies:
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # Draw SVG files
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.2.0+3
  country_picker: ^2.0.26
  custom_rating_bar: ^3.0.0
  pinput: ^5.0.0


  # dio: ^5.0.0
  http: ^1.0.0
  # path: ^1.8.3
  # path_provider: ^2.1.1
  # http_parser: ^4.0.2
  open_settings_plus: ^0.4.0
  # loading_indicator: ^3.1.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  # For image
  # image_picker: ^1.1.2
  # image_cropper: ^9.0.0
  # flutter_image_compress: ^2.4.0
  # cached_network_image: ^3.4.1
  intl: ^0.20.2           # good to keep date/number formats in sync

  # notification
  firebase_core: ^3.14.0
  firebase_auth: ^5.5.1
  # firebase_messaging: ^14.7.9
  flutter_local_notifications: ^19.2.1

  url_launcher: ^6.2.5

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.0
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/category/
    - assets/icons/nav/

flutter_native_splash:
  color: "#0C192B"
  image: assets/images/logo.png
  fullscreen: true

  android_12:
    color: "#0C192B"
    image: assets/images/logo.png
    fullscreen: true

