name: pillo
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  get: 4.6.6
  # A Flutter package to use fonts from fonts.google.com.
  google_fonts: ^6.2.1
  # Draw SVG files
  flutter_svg: ^2.0.10+1
  smooth_page_indicator: ^1.2.0+3
  # A flutter package to select a country from a list of countries.
  country_picker: ^2.0.26

  pinput: ^5.0.0

  flutter:
    sdk: flutter
  # A flutter plugin for adapting screen and font size.Let your UI display a reasonable layout on different screen sizes!
  flutter_screenutil: ^5.9.3
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_lints: 4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/icons/nav/
    - assets/icons/category/

flutter_native_splash:
  color: "#0C192B"
  image: assets/images/logo.png
  fullscreen: true
